name: Deploy

on:
  push:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'harryzcy'
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.cloudflare.com:443
            api.github.com:443
            github.com:443
            nodejs.org:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            registry.npmjs.org:443
            sparrow.cloudflare.com:443

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26
          check-latest: true

      - name: Extract branch name
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" =~ ^refs/tags/ ]]; then
            echo "branch=main" >> "$GITHUB_OUTPUT"
          else
            echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
          fi
        id: extract_branch

      - name: Build
        run: |
          make build-cloudflare

      - name: Get Wrangler Version
        id: get_wrangler_version
        run: |
          cd cloudflare
          WRANGLER_VERSION=$(npm list wrangler --depth=0 | grep wrangler | awk -F@ '{print $2}')
          echo "wrangler_version=$WRANGLER_VERSION" >> "$GITHUB_OUTPUT"

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name mailbox-browser --branch ${{ steps.extract_branch.outputs.branch }} dist
          workingDirectory: cloudflare
          wranglerVersion: ${{ steps.get_wrangler_version.outputs.wrangler_version }}
