name: Docker Build

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get commit
        run: |
          echo "$(git rev-parse --short "$GITHUB_SHA")" >> $env:BUILD_COMMIT

      - name: Get date
        run: |
          echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $env:BUILD_DATE

      - name: Get version
        run: |
          echo "$(git describe --tags --always)" >> $env:BUILD_VERSION

      - name: Check build variables
        run: |
          echo $BUILD_COMMIT
          echo $BUILD_DATE
          echo $BUILD_VERSION
        env:
          BUILD_COMMIT: ${{ env.BUILD_COMMIT }}
          BUILD_DATE: ${{ env.BUILD_DATE }}
          BUILD_VERSION: ${{ env.BUILD_VERSION }}

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_COMMIT=${{ env.BUILD_COMMIT }}
            BUILD_VERSION=${{ env.BUILD_VERSION }}
          platforms: linux/amd64
          push: false
