name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@16bdbb2247468d7d997e4961b77a2bb17b18767b # main

  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@16bdbb2247468d7d997e4961b77a2bb17b18767b # main
    with:
      working-directory: bff

  prettier:
    name: Prettier
    uses: harryzcy/github-actions/.github/workflows/prettier.yml@16bdbb2247468d7d997e4961b77a2bb17b18767b # main
    with:
      working-directory: web

  eslint:
    name: ESLint
    uses: harryzcy/github-actions/.github/workflows/npm-lint.yml@16bdbb2247468d7d997e4961b77a2bb17b18767b # main
    with:
      working-directory: web
