name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@129e079b7d1fa823cbf277f0030f6dbb516c9098 # main

  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@129e079b7d1fa823cbf277f0030f6dbb516c9098 # main
    with:
      working-directory: bff

  prettier:
    name: Prettier
    uses: harryzcy/github-actions/.github/workflows/prettier.yml@129e079b7d1fa823cbf277f0030f6dbb516c9098 # main
    with:
      working-directory: web

  oxlint:
    name: Oxlint
    uses: harryzcy/github-actions/.github/workflows/npm-lint.yml@129e079b7d1fa823cbf277f0030f6dbb516c9098 # main
    with:
      working-directory: web
