name: Prettier

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, prettier, typescript]

      - name: Install dependencies
        run: pnpm install

      - name: Run prettier
        run: |-
          pnpx prettier --config .prettierrc 'src/**/*.{ts,tsx}' --check
