name: Release Drafter

on:
  push:
    branches:
      - main
    tags-ignore:
      - "v*"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  update:
    name: Generate Notes
    permissions:
      contents: write
      pull-requests: write
    uses: harryzcy/github-actions/.github/workflows/release-drafter.yml@3b3649a8fd8b9986a9e6d3c45174d40488155d3d # main
