name: Release Drafter

on:
  push:
    branches:
      - main
    tags-ignore:
      - "v*"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  update:
    name: Generate Notes
    permissions:
      contents: write
      pull-requests: write
    uses: harryzcy/github-actions/.github/workflows/release-drafter.yml@825de87bb7a41da3f54e6863939129d6dfc82da8 # main
