name: Releases

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    name: Release on GitHub
    permissions:
      contents: write
    uses: harryzcy/github-actions/.github/workflows/release.yml@13a4c40f9699ea2915746978b58bb42160f771b6 # main

  release-docker:
    name: Release on Docker Hub
    if: github.repository_owner == 'harryzcy'
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get build variables
        run: |
          # shellcheck disable=SC2129
          echo "BUILD_COMMIT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$GITHUB_ENV"
          echo "BUILD_VERSION=$(git describe --tags --always)" >> "$GITHUB_ENV"

      - name: Check build variables
        run: |
          echo "$BUILD_COMMIT"
          echo "$BUILD_DATE"
          echo "$BUILD_VERSION"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: |
            harryzcy/mailbox-browser
            ghcr.io/harryzcy/mailbox-browser
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to DockerHub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_COMMIT=${{ env.BUILD_COMMIT }}
            BUILD_VERSION=${{ env.BUILD_VERSION }}
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
